### ISSUE TITLE
I would just like to suggest that you add a note how to add config variables to Heroku

### ISSUE THREAD

**Issue by dirkjbosman** [jessamynsmith/flask-google-sheets#2]
As a new heroku user, I had to dig on how to add the configs.

Would be cool to add thes screenshots to your readme:
https://devcenter.heroku.com/articles/config-vars

Just my two-cents :)
D

**Comment by jessamynsmith** [comment]
I do have deployment instructions in the README, including setting config vars: https://github.com/jessamynsmith/flask-google-sheets#deployment

Did you try to follow these instructions? Did you run into issues? If so, I will update them accordingly.

I tend not to document alternate methods, partly for simplicity and partly because I have limited resources to devote to maintaining sample projects. However, I can see potential value in detailing different methods for deployment. If you want to submit a pull request I will consider it.

**Comment by jessamynsmith** [comment]
I am also hesitant to duplicate too much of the Heroku documentation in my own README. I'd be open to adding a link to it.

**Comment by jessamynsmith** [comment]
Link added.
